### ISSUE TITLE
Cosmic Desktop option. 

### ISSUE THREAD

**Issue by redwingsred** [system76/pop-code-of-conduct#3]
I have a problem with Pop!_Os moving to rust and making their own Desktop environment. They have made a good OS in Ubuntu, a great OS in Pop!_Os. Why fix something that isnt broken? ....(There is an option I need in order to use my monitor. I need the "Adjust for TV" in display options that Gnome has in it. If they stop using Gnome that option will be gone. Pop!_OS is a perfect Linux OS but Ill have to stick with Gnome and will have to abandon Pop. ) Is there any way Pop programmers can add the "Adjust for TV" in the new display options on the new desktop?

**Comment by leviport** [comment]
First of all, the relevant repo for these points is https://github.com/pop-os/cosmic/

You can open a feature request for the "Adjust for TV" feature in https://github.com/pop-os/cosmic/issues, but please make it clear and focused. These feature requests are very useful for helping us learn which features users need or want, but they can easily be filled with noise if they devolve into discussions about whether or not Pop!\_OS should stay on Gnome.

If you want to discuss whether or not Pop!\_OS should continue to use Gnome, I suppose you can open a discussion thread at https://github.com/pop-os/cosmic/discussions. However we're pretty committed to making our own thing, so we probably won't chime in ourselves. Abandoning our efforts because of a single feature that we could implement in our own DE just doesn't seem reasonable to me.

It's also worth noting that keeping Pop compatible with multiple DE's is definitely an objective. If you still want Gnome, you should still be able to use Gnome.
